server:
  port: 8081
  address: 0.0.0.0  # 关键！允许外网访问

spring:
  sql:
    init:
      mode: never  # 可选：always/embedded/never
      schema-locations: classpath:db/ddl/*.sql
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seconhand_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Root@123456
#    password: password

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      location: ${user.dir}/upload/temp

mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.secondhand.entity
  global-config:
    # 👇 关键配置：禁用自动DDL，彻底不加载DdlApplicationRunner
    enable-sql-runner: false
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html